import { escapeHtml } from "./email.ts";

export const SCHEDULE_DAYS: Record<string, number> = {
  weekly: 7,
  monthly: 30,
  quarterly: 90,
};

export interface Finding {
  title: string;
  severity: string;
  detail?: string;
}

export interface ScoreResult {
  overall: number;
  grade: string;
  categories: Array<{ name: string; score: number }>;
}

export function computeSimpleScore(findings: Finding[]): ScoreResult {
  let score = 100;
  for (const f of findings) {
    if (f.severity === "critical") score -= 15;
    else if (f.severity === "high") score -= 8;
    else if (f.severity === "medium") score -= 3;
    else if (f.severity === "low") score -= 1;
  }
  score = Math.max(0, Math.min(100, score));
  const grade = score >= 90
    ? "A"
    : score >= 75
    ? "B"
    : score >= 60
    ? "C"
    : score >= 40
    ? "D"
    : "F";
  return { overall: score, grade, categories: [] };
}

export function buildOnePagerContent(
  customerName: string,
  findings: Finding[],
  score: ScoreResult,
): { subject: string; markdown: string } {
  const severityOrder = ["critical", "high", "medium", "low", "info"];
  const sorted = [...findings].sort(
    (a, b) =>
      severityOrder.indexOf(a.severity) - severityOrder.indexOf(b.severity),
  );
  const top5 = sorted.slice(0, 5);

  const criticalCount =
    findings.filter((f) => f.severity === "critical").length;
  const highCount = findings.filter((f) => f.severity === "high").length;
  const mediumCount = findings.filter((f) => f.severity === "medium").length;

  const safeName = escapeHtml(customerName || "Assessment");
  const lines: string[] = [];
  lines.push(`# Compliance Report — ${safeName}`);
  lines.push("");
  lines.push(
    `**Overall Score:** ${score.overall}/100 | **Grade:** ${score.grade}`,
  );
  lines.push("");
  lines.push(
    `**Findings:** ${criticalCount} Critical · ${highCount} High · ${mediumCount} Medium · ${findings.length} Total`,
  );
  lines.push("");
  lines.push("## Top 5 Risks");
  lines.push("");
  if (top5.length === 0) {
    lines.push("No findings identified — excellent posture.");
  } else {
    top5.forEach((f, i) => {
      lines.push(
        `${i + 1}. **${escapeHtml(f.title)}** — *${escapeHtml(f.severity)}*`,
      );
    });
  }
  lines.push("");
  lines.push("## Recommended Next Steps");
  lines.push("");
  lines.push("1. Address critical and high severity findings first.");
  lines.push("2. Review and remediate the top 5 risks listed above.");
  lines.push("3. Schedule a follow-up assessment after remediation.");

  const subject =
    `${safeName} Compliance Report — Score: ${score.overall}/100 (${score.grade})`;
  return { subject, markdown: lines.join("\n") };
}

export function markdownToHtml(md: string): string {
  let html = md
    .replace(/^### (.+)$/gm, "<h3>$1</h3>")
    .replace(
      /^## (.+)$/gm,
      '<h2 style="margin-top:24px;margin-bottom:8px;font-size:18px;color:#111;">$1</h2>',
    )
    .replace(
      /^# (.+)$/gm,
      '<h1 style="margin-top:0;margin-bottom:16px;font-size:24px;color:#111;">$1</h1>',
    )
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g, "<em>$1</em>")
    .replace(/^\d+\. (.+)$/gm, "<li>$1</li>")
    .replace(/^- (.+)$/gm, "<li>$1</li>");

  html = html.replace(
    /((?:<li>.*<\/li>\n?)+)/g,
    '<ol style="padding-left:20px;margin:8px 0;">$1</ol>',
  );
  html = html.replace(/\n{2,}/g, "<br/><br/>");
  html = html.replace(/\n/g, "<br/>");

  return html;
}

export function buildEmailHtml(
  bodyHtml: string,
  orgName: string,
  logoUrl?: string,
): string {
  const safeOrg = escapeHtml(orgName);
  const logo = logoUrl
    ? `<img src="${logoUrl}" alt="${safeOrg}" style="max-height:40px;max-width:200px;margin-bottom:16px;" />`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"/><meta name="viewport" content="width=device-width,initial-scale=1"/></head>
<body style="margin:0;padding:0;background:#f4f4f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;">
  <div style="max-width:640px;margin:0 auto;background:#ffffff;border-radius:8px;overflow:hidden;margin-top:24px;margin-bottom:24px;box-shadow:0 1px 3px rgba(0,0,0,0.1);">
    <div style="background:#0a0f1e;padding:24px 32px;color:#ffffff;">
      ${logo}
      <p style="margin:0;font-size:12px;opacity:0.7;">${safeOrg}</p>
    </div>
    <div style="padding:32px;color:#333;font-size:14px;line-height:1.6;">
      ${bodyHtml}
    </div>
    <div style="padding:16px 32px;background:#f9fafb;border-top:1px solid #e5e7eb;font-size:11px;color:#9ca3af;text-align:center;">
      Generated by FireComply · <a href="https://sophos-firecomply.vercel.app" style="color:#2006F7;text-decoration:none;">Open Dashboard</a>
    </div>
  </div>
</body>
</html>`;
}

export function extractFindingsFromSubmissions(
  submissions: Array<{ full_analysis: unknown; customer_name: unknown }>,
): Finding[] {
  const allFindings: Finding[] = [];
  for (const sub of submissions) {
    const analysis = sub.full_analysis as Record<string, unknown> | null;
    if (analysis && Array.isArray(analysis.findings)) {
      for (const f of analysis.findings) {
        if (
          f && typeof f === "object" && "title" in f && "severity" in f
        ) {
          allFindings.push({
            title: String(f.title),
            severity: String(f.severity),
            detail: String((f as Record<string, unknown>).detail ?? ""),
          });
        }
      }
    }
  }
  return allFindings;
}

/** Subject, markdown, and HTML for a scheduled one-pager (preview + send). */
export function buildScheduledReportContent(
  report: {
    customer_name: string | null;
    recipients: unknown;
  },
  org: { name?: string; logo_url?: string } | undefined,
  submissions: Array<{ full_analysis: unknown; customer_name: unknown }>,
  opts?: { requireRecipients?: boolean },
): { subject: string; markdown: string; html: string } | { error: string } {
  const recipients = (report.recipients as string[]) ?? [];
  const requireRecipients = opts?.requireRecipients ?? true;
  if (requireRecipients && recipients.length === 0) {
    return { error: "No recipients" };
  }

  const findings = extractFindingsFromSubmissions(submissions);
  const customerName = report.customer_name ||
    (submissions[0]?.customer_name as string) || "Client";
  const score = computeSimpleScore(findings);
  const { subject, markdown } = buildOnePagerContent(
    customerName,
    findings,
    score,
  );
  const orgName = org?.name ?? "FireComply";
  const logoUrl = org?.logo_url ?? undefined;
  const bodyHtml = markdownToHtml(markdown);
  const emailHtml = buildEmailHtml(bodyHtml, orgName, logoUrl);
  return { subject, markdown, html: emailHtml };
}

export function computeNextDue(schedule: string, from: Date): string {
  const days = SCHEDULE_DAYS[schedule] ?? 30;
  const next = new Date(from.getTime() + days * 86_400_000);
  return next.toISOString();
}

export async function sendScheduledReportEmail(
  to: string[],
  subject: string,
  html: string,
): Promise<{ success: boolean; error?: string }> {
  const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY") ?? "";
  const FROM_EMAIL = Deno.env.get("REPORT_FROM_EMAIL") ??
    "reports@firecomply.io";

  if (!RESEND_API_KEY) {
    return { success: false, error: "RESEND_API_KEY not configured" };
  }

  try {
    const resp = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: FROM_EMAIL,
        to,
        subject,
        html,
      }),
    });

    if (!resp.ok) {
      const body = await resp.text();
      return {
        success: false,
        error: `Email delivery failed: ${resp.status} ${body.slice(0, 200)}`,
      };
    }

    return { success: true };
  } catch (err) {
    return {
      success: false,
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

export type ScheduledReportJobPayload = {
  scheduled_report_id: string;
};

export function scheduledReportIdempotencyKey(
  reportId: string,
  nextDueAt: string,
): string {
  return `scheduled_report:${reportId}:${nextDueAt}`;
}
