import { z } from "npm:zod@3.24.2";
import { authenticateSE } from "../../_shared/auth.ts";
import { json as jsonResponse, safeError } from "../../_shared/db.ts";
import {
  buildSophosEmailHtml,
  CONFIG_UPLOAD_FROM_EMAIL,
  escapeHtml,
  RESEND_API_KEY,
} from "../../_shared/email.ts";
import { logJson } from "../../_shared/logger.ts";

export const sendReportBodySchema = z
  .object({
    customer_email: z.string().email().max(320),
    customer_name: z.string().max(500).optional(),
    prepared_for: z.string().max(500).optional(),
    prepared_by: z.string().max(500).optional(),
    se_title: z.string().max(500).optional(),
    pdf_base64: z.string().max(50_000_000).optional(),
    html_base64: z.string().max(50_000_000).optional(),
    filename_base: z.string().max(200).optional(),
  })
  .refine((b) => Boolean(b.pdf_base64?.trim() || b.html_base64?.trim()), {
    message: "At least one of pdf_base64 or html_base64 is required",
  });

export async function handleSendReportRoutes(
  req: Request,
  _url: URL,
  segments: string[],
  corsHeaders: Record<string, string>,
): Promise<Response | null> {
  function json(
    body: unknown,
    status = 200,
    headers: Record<string, string> = corsHeaders,
  ) {
    return jsonResponse(body, status, headers);
  }

  if (
    !(req.method === "POST" && segments[0] === "send-report" &&
      segments.length === 1)
  ) {
    return null;
  }

  const se = await authenticateSE(req);
  if (!se) return json({ error: "Unauthorized" }, 401);

  const raw = await req.json().catch(() => ({}));
  const parsed = sendReportBodySchema.safeParse(raw);
  if (!parsed.success) {
    logJson("warn", "send_report_invalid_body", {
      issues: parsed.error.issues.length,
    });
    return json({ error: "Invalid request body" }, 400);
  }
  const {
    customer_email,
    customer_name,
    prepared_for,
    prepared_by,
    se_title,
    pdf_base64,
    html_base64,
    filename_base,
  } = parsed.data;

  const seName = se.seProfile.display_name || se.seProfile.email || "Your SE";
  const recipientGreeting = escapeHtml(
    prepared_for || customer_name || "Customer",
  );
  const signOffName = escapeHtml(prepared_by || seName);
  const forClause = customer_name
    ? ` for <strong>${escapeHtml(customer_name)}</strong>`
    : "";
  const titleLine = se_title ? `<br/>${escapeHtml(se_title)}` : "";
  const subjectName = customer_name || prepared_for || "Customer";
  const base = filename_base || "Sophos-Firewall-Health-Check";

  const attachments: Array<{ filename: string; content: string }> = [];
  if (pdf_base64) {
    attachments.push({ filename: `${base}.pdf`, content: pdf_base64 });
  }
  if (html_base64) {
    attachments.push({ filename: `${base}.html`, content: html_base64 });
  }

  const emailHtml = buildSophosEmailHtml(
    "Firewall Health Check Report",
    `<p>Hi ${recipientGreeting},</p>
       <p>Please find your Sophos Firewall Health Check report attached${forClause}. This report includes a comprehensive assessment of your firewall configuration with recommendations for improvement.</p>
       <p>If you have any questions about the findings, please don't hesitate to reach out.</p>
       <p style="margin-top:16px;">Best regards,<br/>${signOffName}${titleLine}</p>`,
    undefined,
    undefined,
    "This report was generated by Sophos FireComply.",
  );

  if (!RESEND_API_KEY) {
    return json({ error: "RESEND_API_KEY not configured" }, 500);
  }

  try {
    const resp = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: CONFIG_UPLOAD_FROM_EMAIL,
        to: [customer_email],
        subject: `Sophos Firewall Health Check Report — ${subjectName}`,
        html: emailHtml,
        attachments,
      }),
    });
    if (!resp.ok) {
      const errBody = await resp.text();
      logJson("error", "send_report_email_provider_failed", {
        status: resp.status,
        bodyPrefix: errBody.slice(0, 500),
      });
      return json({ error: "Email delivery failed" }, 500);
    }
    return json({ ok: true });
  } catch (err) {
    return json({ error: safeError(err, "Email delivery failed") }, 500);
  }
}
