import { authenticateSE } from "../../_shared/auth.ts";
import { json as jsonResponse } from "../../_shared/db.ts";
import { buildSophosEmailHtml, CONFIG_UPLOAD_FROM_EMAIL, escapeHtml, RESEND_API_KEY } from "../../_shared/email.ts";

export async function handleSendReportRoutes(
  req: Request,
  _url: URL,
  segments: string[],
  corsHeaders: Record<string, string>,
): Promise<Response | null> {
  function json(body: unknown, status = 200, headers: Record<string, string> = corsHeaders) {
    return jsonResponse(body, status, headers);
  }

  if (!(req.method === "POST" && segments[0] === "send-report" && segments.length === 1)) {
    return null;
  }

  const se = await authenticateSE(req);
  if (!se) return json({ error: "Unauthorized" }, 401);

  const body = await req.json();
  const { customer_email, customer_name, prepared_for, prepared_by, se_title, pdf_base64, html_base64, filename_base } = body as {
    customer_email?: string;
    customer_name?: string;
    prepared_for?: string;
    prepared_by?: string;
    se_title?: string;
    pdf_base64?: string;
    html_base64?: string;
    filename_base?: string;
  };

  if (!customer_email) return json({ error: "customer_email is required" }, 400);
  if (!pdf_base64 && !html_base64) return json({ error: "At least one of pdf_base64 or html_base64 is required" }, 400);

  const seName = se.seProfile.display_name || se.seProfile.email || "Your SE";
  const recipientGreeting = escapeHtml(prepared_for || customer_name || "Customer");
  const signOffName = escapeHtml(prepared_by || seName);
  const forClause = customer_name ? ` for <strong>${escapeHtml(customer_name)}</strong>` : "";
  const titleLine = se_title ? `<br/>${escapeHtml(se_title)}` : "";
  const subjectName = customer_name || prepared_for || "Customer";
  const base = filename_base || "Sophos-Firewall-Health-Check";

  const attachments: Array<{ filename: string; content: string }> = [];
  if (pdf_base64) attachments.push({ filename: `${base}.pdf`, content: pdf_base64 });
  if (html_base64) attachments.push({ filename: `${base}.html`, content: html_base64 });

  const emailHtml = buildSophosEmailHtml(
    "Firewall Health Check Report",
    `<p>Hi ${recipientGreeting},</p>
       <p>Please find your Sophos Firewall Health Check report attached${forClause}. This report includes a comprehensive assessment of your firewall configuration with recommendations for improvement.</p>
       <p>If you have any questions about the findings, please don't hesitate to reach out.</p>
       <p style="margin-top:16px;">Best regards,<br/>${signOffName}${titleLine}</p>`,
    undefined,
    undefined,
    "This report was generated by Sophos FireComply."
  );

  if (!RESEND_API_KEY) return json({ error: "RESEND_API_KEY not configured" }, 500);

  try {
    const resp = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: CONFIG_UPLOAD_FROM_EMAIL,
        to: [customer_email],
        subject: `Sophos Firewall Health Check Report — ${subjectName}`,
        html: emailHtml,
        attachments,
      }),
    });
    if (!resp.ok) {
      const errBody = await resp.text();
      return json({ error: `Email send failed: ${errBody}` }, 500);
    }
    return json({ ok: true });
  } catch (err) {
    return json({ error: String(err) }, 500);
  }
}
