import { z } from "npm:zod@3.24.2";
import { getOrgMembership } from "../../_shared/auth.ts";
import {
  adminClient,
  json as jsonResponse,
  safeError,
  userClient,
} from "../../_shared/db.ts";
import {
  buildSophosEmailHtml,
  CONFIG_UPLOAD_FROM_EMAIL,
  escapeHtml,
  RESEND_API_KEY,
} from "../../_shared/email.ts";
import { logJson } from "../../_shared/logger.ts";

const bodySchema = z.object({
  saved_report_id: z.string().uuid(),
  recipient_email: z.string().email().max(320),
  /** UTF-8 HTML document (same pipeline as saved report viewer → buildReportHtml). */
  html_base64: z.string().min(8).max(50_000_000),
  /** Shown in subject / greeting; defaults to stored customer name. */
  customer_display_name: z.string().max(500).optional(),
  prepared_by: z.string().max(500).optional(),
});

export async function handleSendSavedLibraryReportRoutes(
  req: Request,
  _url: URL,
  segments: string[],
  corsHeaders: Record<string, string>,
): Promise<Response | null> {
  function json(
    body: unknown,
    status = 200,
    headers: Record<string, string> = corsHeaders,
  ) {
    return jsonResponse(body, status, headers);
  }

  const isPrimaryPath = req.method === "POST" &&
    segments[0] === "send-saved-library-report" &&
    segments.length === 1;
  const isSendReportAlias = req.method === "POST" &&
    segments[0] === "send-report" &&
    segments[1] === "saved-library" && segments.length === 2;
  if (!isPrimaryPath && !isSendReportAlias) {
    return null;
  }

  const authHeader = req.headers.get("authorization");
  if (!authHeader) return json({ error: "Unauthorized" }, 401);

  const uc = userClient(authHeader);
  const {
    data: { user },
  } = await uc.auth.getUser();
  if (!user) return json({ error: "Unauthorized" }, 401);

  const membership = await getOrgMembership(user.id);
  if (!membership) {
    return json({ error: "Not a member of any organisation" }, 403);
  }

  const raw = await req.json().catch(() => ({}));
  const parsed = bodySchema.safeParse(raw);
  if (!parsed.success) {
    logJson("warn", "send_saved_library_report_invalid_body", {
      issues: parsed.error.issues.length,
    });
    return json({ error: "Invalid request body" }, 400);
  }

  const {
    saved_report_id,
    recipient_email,
    html_base64,
    customer_display_name,
    prepared_by,
  } = parsed.data;

  const db = adminClient();
  const { data: row, error: rowErr } = await db
    .from("saved_reports")
    .select("id, org_id, customer_name")
    .eq("id", saved_report_id)
    .maybeSingle();

  if (rowErr || !row) {
    return json({ error: "Saved report not found" }, 404);
  }
  if ((row as { org_id: string }).org_id !== membership.org_id) {
    return json({ error: "Forbidden" }, 403);
  }

  const storedName =
    (row as { customer_name?: string }).customer_name?.trim() || "Customer";
  const subjectName = (customer_display_name?.trim() || storedName).slice(
    0,
    500,
  );
  const signOff = escapeHtml(
    (prepared_by?.trim() || user.email || "Your team").slice(0, 500),
  );
  const greeting = escapeHtml(subjectName);

  const cleanB64 = html_base64.replace(/\s/g, "");
  if (cleanB64.length < 16) {
    return json({ error: "Report HTML payload is too small" }, 400);
  }
  if (!/^[A-Za-z0-9+/]+=*$/.test(cleanB64)) {
    return json({ error: "Invalid html_base64" }, 400);
  }
  const approxDecodedBytes = Math.floor((cleanB64.length * 3) / 4);
  if (approxDecodedBytes > 12 * 1024 * 1024) {
    return json({ error: "Report HTML is too large" }, 413);
  }

  const safeFile =
    subjectName.replace(/[^\w-]+/g, "-").replace(/^-|-$/g, "").slice(0, 80) ||
    "report";
  const emailHtml = buildSophosEmailHtml(
    "Firewall Configuration Assessment Report",
    `<p>Hi ${greeting},</p>
       <p>Please find your Sophos FireComply assessment report attached (HTML). Open the file in a browser for the full layout.</p>
       <p>If you have any questions about the findings, please reach out.</p>
       <p style="margin-top:16px;">Best regards,<br/>${signOff}</p>`,
    undefined,
    undefined,
    "This report was generated by Sophos FireComply.",
  );

  if (!RESEND_API_KEY) {
    return json({ error: "RESEND_API_KEY not configured" }, 500);
  }

  try {
    const resp = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        Authorization: `Bearer ${RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: CONFIG_UPLOAD_FROM_EMAIL,
        to: [recipient_email],
        subject: `Firewall Configuration Assessment Report — ${subjectName}`,
        html: emailHtml,
        attachments: [
          {
            filename: `${safeFile}-FireComply-report.html`,
            content: cleanB64,
          },
        ],
      }),
    });
    if (!resp.ok) {
      const errBody = await resp.text();
      logJson("error", "send_saved_library_report_resend_failed", {
        status: resp.status,
        bodyPrefix: errBody.slice(0, 500),
      });
      return json({ error: "Email delivery failed" }, 500);
    }
    return json({ ok: true });
  } catch (err) {
    return json({ error: safeError(err, "Email delivery failed") }, 500);
  }
}
